#!/usr/bin/env bash

target_path="$HOME/.pathfind"
function permission_violation() {
    echo ""
    echo "User Status: Forbidden"
    echo "[App Manager Setup] Permission Violation; cannot run as root. This is very dangerous, please run as a normal user."
    echo ""
    exit 13
}

function create_target_path() {
    mkdir -p $target_path && echo "Created path at: $target_path" || exit 4
    echo "export PATH=$PATH:$target_path" >> $HOME/.bashrc
    source $HOME/.bashrc
}

function invalid_path() {
    abs_path=$1
    [[ -d "$abs_path" ]] && echo "[App Manager - Setup] PATH '$abs_path' was flagged as invalid, but DOES exist. This error should NOT be possible." || echo "[App Manager - Setup] PATH '$abs_path' is an invalid path or does not exist."
    exit 4
}

function use_default_path() {
    target_path="$HOME/.pathfind"
    echo "[App Manager - Setup] Using default PATH: $target_path" && echo ""
    grep -i "KJ_APPMAN_DIR=" $HOME/.bashrc && echo "OK" || echo "KJ_APPMAN_DIR=$PWD/app-manager" >> $HOME/.bashrc
}

function use_custom_path() {
    echo "Checking for valid path..."
    [[ -d "$target_path" ]] && echo "[App Manager - Setup] OK, using custom PATH: $target_path" || invalid_path $target_path
    grep -i "KJ_APPMAN_DIR=" $HOME/.bashrc && echo "OK" || echo "KJ_APPMAN_DIR=$PWD/app-manager" >> $HOME/.bashrc
    echo ""
}

function download_and_setup_app_manager() {
    echo "Please provide an absolute path. [Leave this space empty for the default '.pathfind' path in your home directory.]"; echo "Enter Path: "
    read target_path
    [[ -z $target_path ]] && use_default_path || use_custom_path $target_path
    download_uri="https://github.com/Suzuko-Nakajima/app-manager.git"
    git clone $download_uri && sleep 1
    cd ./app-manager; chmod 755 ./app-manager && ./app-manager --version
    [[ -d $target_path ]] && echo "Target path located." || create_target_path
    ln -fs $PWD/app-manager $target_path && source $HOME/.bashrc
}

function main() {
    [[ "$(id -u)" -eq 0 ]] && permission_violation || echo "User Status: OK" # Fail with exit code 13 if ran as sudo, otherwise, print an "OK" status.
    download_and_setup_app_manager
}

main